### ISSUE TITLE
TypeError: '<' not supported between instances of 'list' and 'int'

### ISSUE THREAD

**Issue by hugocartwright** [hugocartwright/sungai#16]
**Describe the bug**
Preprocess sort issue

**To Reproduce**
1. python -m venv venv
2. source venv/bin/activate
3. pip install sungai==0.1.4
4. git clone https://github.com/scikit-learn/scikit-learn/
5. cd scikit-learn
6. git checkout 1.2.2
7. sungai sklearn/datasets/tests/data/openml/ --min_score 1
8. See error
9. deactivate

**Expected behavior**
Usual sungai output

**Error**
Sungai (0.1.4)
Traceback (most recent call last):
  File "/usr/local/bin/sungai", line 8, in <module>
    sys.exit(run_sungai())
  File "/usr/local/lib/python3.10/site-packages/sungai/__init__.py", line 57, in run_sungai
    directory_rater.run(
  File "/usr/local/lib/python3.10/site-packages/sungai/sungai.py", line 248, in run
    self.preprocess()
  File "/usr/local/lib/python3.10/site-packages/sungai/sungai.py", line 186, in preprocess
    self.structure.sort(reverse=True)
TypeError: '<' not supported between instances of 'list' and 'int'

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by hugocartwright** [comment]
Fixed in version 0.1.5
